---
# defaults file for common
mokapot_debian_reqs:
  - wapiti #web application vulnerability scanner
  - recon-ng #Web Reconnaissance framework written in Python
  - hping3 #Active Network Smashing Tool
  - hashcat #The Network Mapper
  - nmap #Security Scanner, Port Scanner, Network Exploration
  - traceroute #Traces the route taken by packets over an IPv4/IPv6 network
  - mtr #Full screen ncurses and X11 traceroute tool
  - tcpdump #command-line network traffic analyzer
  - ssdeep #recursive piecewise hashing tool fuzzy hashing 	https://ssdeep-project.github.io/ssdeep/index.html
  - socat #multipurpose relay for bidirectional data transfer
  - traceroute #network diagnostic tool
  - mtr #network diagnostic tool
  - net-tools
######################
  # - ncat #- NMAP netcat reimplementation
  # - p0f #- Passive OS fingerprinting tool
  # - pnscan #- Multi threaded port scanner
  # - masscan #- TCP port scanner
  # - ncrack #- High-speed network authentication cracking tool
  # - ndiff #- The Network Mapper - result compare utility
  # - netsniff-ng #- Linux network packet sniffer toolkit
  # - dnsdiag #- DNS request auditing toolset
  # - argus-server #- IP network transaction auditing tool
  # - argus-client #- IP network transaction auditing tool
  # - dhcpdump #- Parse DHCP packets from tcpdump
  # - mitmproxy #- SSL-capable man-in-the-middle HTTP proxy
  # - namebench #- DNS benchmark utility
  # - ncaptool #- network capture tool
  # - ngrep #- grep for network traffic
  # - nstreams #- network streams - a tcpdump output analyzer
  # - packit #- network packet generator and capture tool
  # - python-scapy #- Packet generator/sniffer and network scanner/discovery (Python 2)
  # - python3-scapy #- Packet generator/sniffer and network scanner/discovery (Python 3)
  # - ssldump #- SSLv3/TLS network protocol analyzer
  # - tcpflow #- TCP flow recorder
  # - tcpflow-nox #- TCP flow recorder - version without X11 dependencies
  # - tcpreplay #- Tool to replay saved tcpdump files at arbitrary speeds
  # - tcpslice #- extract pieces of and/or glue together tcpdump files
  # - tcpspy #- Incoming and Outgoing TCP/IP connections logger
  # - tcpstat #- network interface statistics reporting tool
  # - tcptrace #- Tool for analyzing tcpdump output
  # - tcpick #- TCP stream sniffer and connection tracker
  # - tcpxtract #- extract files from network traffic based on file signatures
  # - pcapfix #- repairs broken pcap and pcapng files
  # - nsntrace #- perform network trace of a single process by using network namespaces
  # - ostinato #- Packet/Traffic Generator and Analyzer
  ######################
  - brutespray #- Python bruteforce tool
  - sec #Simple Event Correlator https://simple-evcorr.github.io/
  - wireshark #network traffic analyzer
  - tshark # network traffic analyzer - console version
  - hydra #very fast network logon cracker parallelized login cracker
  - dnsutils # dig DNS lookup utility Clients provided with BIND
  - netcat #- TCP/IP swiss army knife -- transitional package
  - netcat-traditional #TCP/IP swiss army knife
  - netcat-openbsd #TCP/IP swiss army knife arbitrary TCP and UDP connections and listens https://packages.debian.org/buster/netcat
  - dirb #URL bruteforcing tool web Content Scanner
  - aircrack-ng #wireless WEP/WPA cracking utilities Wireless Security Auditing
  - wifite #- Python script to automate wireless auditing using aircrack-ng tools
  - kismet #- wireless sniffer and monitor layer-2 wireless network detector, sniffer, and intrusion detection system
  - gddrescue  #- GNU data recovery tool
  - sleuthkit #- tools for forensics analysis on volume and filesystem data
  - autopsy #- graphical interface to SleuthKit
  - mac-robber #- collects data about allocated files in mounted filesystems
  - clamav #- anti-virus utility for Unix - command-line interface

  ######################
  # - nagios4 #- host/service/network monitoring and management system
  # - zabbix-server-mysql #- network monitoring solution - server (using MySQL)
  # - zabbix-server-pgsql #- network monitoring solution - server (using PostgreSQL)
  # - zabbix-agent #- network monitoring solution - agent
  # - zabbix-cli #- Command-line interface for Zabbix monitoring system
  # - The Sleuth Kit a library and collection of command line tools that allow you to investigate disk images
  # - https://www.sleuthkit.org/sleuthkit/
  # - Autopsy 	a graphical interface to the command line digital forensic analysis tools in The Sleuth Kit 	https://www.sleuthkit.org/autopsy//
  # - nikto #web Vulnerability Scanner
  # - clamav #maldet blazescan https://github.com/Hestat/lw-yara https://github.com/Hestat/blazescan
  # - hexdump #tool to make (or reverse) a hex dump
  #- dd 	#utility can copy and convert simple files, device drivers
mokapot_redhat_reqs:
  - hping3
  - hashcat
  - nikto
  - nmap
  - traceroute
  - mtr
  - tcpdump
  - ssdeep
mokapot_arclinux_reqs:
  - netctl
  - openvpn
  - wpa_supplicant
  - aria2
  - curl
  - htop
  - httpie
  - iotop
  - jq
  - less
  - nmap
  - openssh
  - ripgrep
  - rsync
  - shellcheck
  - usbutils
  - which
  - chromium
  - evince
  - mpv
  - pcmanfm
  - viewnior
      # - wapiti
      # - recon-ng
      # - hping3
      # - hashcat
      # - nikto
      # - nmap
      # - traceroute
      # - mtr
      # - tcpdump
      # - ssdeep
