---
- name: update pacman cache
  pacman:
    update_cache: true


- name: Install pacman tools
  pacman:
    name: pacman-contrib


- name: Install reflector
  pacman:
    name: reflector


- name: update pacman mirrorlist
  script: update-mirrorlist.sh


- name: Install base metapackage
  pacman:
    name: base


- name: perform full upgrade
  pacman:
    upgrade: true
    update_cache: true

- name: Install filesystem tools
  pacman:
    name:
      - cryptsetup
      - e2fsprogs

- name: Install python development tools
  pacman:
    name:
      - python
      - python-pip
      - python-virtualenv

- name: Install golang
  pacman:
    name: go

- name: Install C/C++ development tools
  pacman:
    name:
      - base-devel
      - gdb
      - valgrind    
