---
- name: update pacman cache
  pacman:
    update_cache: true


- name: Install pacman tools
  pacman:
    name: pacman-contrib


- name: Install reflector
  pacman:
    name: reflector


- name: update pacman mirrorlist
  script: update-mirrorlist.sh


- name: Install base metapackage
  pacman:
    name: base


- name: perform full upgrade
  pacman:
    upgrade: true
    update_cache: true
