---
- name: update pacman cache
  pacman:
    update_cache: true


- name: Install pacman tools
  pacman:
    name: pacman-contrib


- name: Install reflector
  pacman:
    name: reflector


- name: update pacman mirrorlist
  script: update-mirrorlist.sh


- name: Install base metapackage
  pacman:
    name: base


- name: perform full upgrade
  pacman:
    upgrade: true
    update_cache: true

- name: Install filesystem tools
  pacman:
    name:
      - cryptsetup
      - e2fsprogs

- name: Install python development tools
  pacman:
    name:
      - python
      - python-pip
      - python-virtualenv

- name: Install golang
  pacman:
    name: go

- name: Install C/C++ development tools
  pacman:
    name:
      - base-devel
      - gdb
      - valgrind

- name: Install docker and pip for ansible management
  pacman: name={{item}}
  with_items:
       - docker
       - docker-compose
       - python2-pip
       - python2
  service:
    name: docker
    enabled: yes

# - name: Install pip packages for ansible
#   pip: name= "{{ item }}" executable=/usr/bin/pip2
#   become: true
#   # pip: name={{ item }}
#   with_items:
#     - setuptools
#     - docker-py
#
# - name: Install docker-gen
#   unarchive:
#     src: https://github.com/jwilder/docker-gen/releases/download/0.7.3/docker-gen-linux-amd64-0.7.3.tar.gz
#     dest: /usr/local/bin/
#     remote_src: True
