---

# Burp Suite version to install
burpsuite_version: "2020.4.1"

# Which Burp Suite product type. Valid values are 'community' or 'pro'
burpsuite_product_type: community

# Directory to install Burp Suite
burpsuite_dir: "/opt/BurpSuite{{ burpsuite_product_type | capitalize }}"

# Directory where Burp Suite installer is located.
burpsuite_installer_dir: /tmp

# Download URL for Burp Suite Community if Community installer is not found
burpsuite_community_download_url: "https://portswigger.net/burp/releases/download?product=community&type=linux&version={{ burpsuite_version }}"

# User for activation of Burp Suite, download CA cert, user config
burpsuite_user: root

# Checksum for the burpsuite_installer script
# If not configured, it will be automatically set based on product type and version from _burpsuite_installer_sha256_checksums in vars/main.yml
# burpsuite_installer_sha256_checksum: ""

# Perform extra tasks for Burp Suite including:
# - automated license installation/acceptance of terms and conditions
# - download CA certificate
# - download JRuby and Jython standalone jars
# - deploy user config file
burpsuite_extras_enabled: true
# Directory for Burp Suite extras
burpsuite_extras_dir: /opt/BurpSuiteExtras

# URLs and checksums for JRuby and Jython jar files
burpsuite_extras_jruby_jar_url: "https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.2.11.1/jruby-complete-9.2.11.1.jar"
burpsuite_extras_jruby_jar_checksum: "78aa284f9b011173dc2b72bc1c8593a3606aacf3"
burpsuite_extras_jython_jar_url: "https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar"
burpsuite_extras_jython_jar_checksum: "15592c29538abd36d15570eda9fa055ed1a618ba"

# Path to the Burp Suite Pro license file
burpsuite_extras_pro_license_path: ""

# Location to save the Burp Suite CA certificate
burpsuite_extras_cacert_path: "{{ burpsuite_extras_dir }}/PortSwigger_CA.der"
