---
- name: Install Nullinux dependencies
  apt:
    name: "{{ null_packages }}"
    state: present

- name: Clone Nullinux repo
  git:
    repo: "{{ null_repo_url }}"
    dest: "{{ null_src_dir }}"
    version: master
  register: clone_nullinux

- name: Copy script to /usr/local/bin
  copy:
    src: "{{ null_src_dir }}/nullinux.py"
    dest: "/usr/local/bin/nullinux.py"
  when: clone_nullinux is changed
