---
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
      - default.yml

# - name: "Install system packages"
#   package:
#     name: '{{ system_packages }}'
#     use: '{{ ansible_pkg_mgr }}'
#     state: present

- include_tasks: pacman.yml

- name: "Install required packages"
  package: pkg={{ item }} state=present update_cache=yes
  with_items:
  - bridge-utils
  - libreadline-dev
  # - libpcap-ruby "No package matching 'libpcap-ruby' is available"}
  - libpq5
  - libpq-dev
  - libsqlite3-dev
  - libpcap-dev
  - libxml2-dev
  - libxslt1-dev
  - libyaml-dev
  - libpq5
  - libpcap-ruby
  - libncap44
  - nmap
  # - openjdk-7-jre "No package matching 'openjdk-7-jre' is available"}
  - pgadmin3
  - postgresql
  - tcpdump
  - vncviewer
  - python-dev
