---
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
      - default.yml

- name: "Install system packages"
  package:
    name: '{{ system_packages }}'
    use: '{{ ansible_pkg_mgr }}'
    state: present

# - name: Install filesystem tools
#   pacman:
#     name:
#       - cryptsetup
#       - e2fsprogs
#
# - name: Install python development tools
#   pacman:
#     name:
#       - python
#       - python-pip
#       - python-virtualenv
#
# - name: Install golang
#   pacman:
#     name: go
#
# - name: Install C/C++ development tools
#   pacman:
#     name:
#       - base-devel
#       - gdb
#       - valgrind

- name: "mokapot requirements"
  package:
    name: "{{ mokapot_arclinux_reqs }}"
    state: present

# - include_tasks: pacman.yml
