---
#https://docs.ansible.com/ansible/2.3/include_vars_module.html
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    -  "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - default.yml


- name: "Install system packages"
  package:
    name: '{{ system_packages }}'
    use: '{{ ansible_pkg_mgr }}'
    state: present

- name: "mokapot requirements"
  package:
    name: "{{ mokapot_debian_reqs }}"
    state: present

- name: "git checkout blazescan (clamav - maldet - blazescan)"
  git:
    repo: 'https://github.com/Hestat/blazescan.git'
    dest: /tmp/mokapot/blazescan
    clone: yes
    update: no
- name: "Install (clamav - maldet - blazescan)"
  shell: install.sh chdir=/tmp/mokapot/blazescan >> /tmp/blazescan_make.out
  args:
    chdir: /tmp
    creates: blazescan_make.out
- name: "git checkout maldet (clamav - maldet - blazescan)"
  git:
    repo: 'https://github.com/Hestat/lw-yara.git'
    dest: /tmp/mokapot/blazescan
    clone: yes
    update: no

#https://github.com/sullo/nikto
- name: "git checkout nikto"
  git:
    repo: 'https://github.com/sullo/nikto'
    dest: /tmp/mokapot/nikto
    clone: yes
    update: no
- name: "Install (clamav - maldet - blazescan)"
  shell: ./nikto.pl chdir=/tmp/mokapot/nikto/program >> /tmp/nikto.pl.out
  args:
    chdir: /tmp
    creates: nikto.pl.out
