---
- name: "Add debian buster nonfree repos"
  blockinfile:
    path: /etc/apt/sources.list
    backup: yes
    block: |
      deb [arch=amd64] http://ftp.gr.debian.org/debian/ buster main contrib non-free
      deb-src [arch=amd64] http://ftp.gr.debian.org/debian/ buster main contrib non-free

      deb [arch=amd64] http://ftp.gr.debian.org/debian/ buster-updates main contrib non-free
      deb-src [arch=amd64] http://ftp.gr.debian.org/debian/ buster-updates main contrib non-free

      deb [arch=amd64] http://security.debian.org/ buster/updates main contrib non-free
      deb-src [arch=amd64] http://security.debian.org/ buster/updates main contrib non-free
# [WARNING]: Could not find aptitude. Using apt-get instead fix
- name: "APT: Install aptitude package"
  apt:
   name: aptitude
   force_apt_get: yes
- name: "Install mokapot requirements"
  apt:
    name: "{{ mokapot_debian_reqs }}"
    state: present
# - name: "git checkout nipper"
#   git:
#     repo: 'https://github.com/arpitn30/nipper-ng.git'
#     dest: /tmp/mokapot/nipper-ng
#     clone: yes
#     update: no
# - name: "Make nipper-ng"
#   shell: make chdir=/tmp/mokapot/nipper-ng/0.11.10 >> /tmp/nipper-ng_make.out
#   args:
#     chdir: /tmp
#     creates: nipper-ng_make.out
# - name: "Make install nipper-ng"
#   shell: make install chdir=/tmp/mokapot/nipper-ng/0.11.10 >> /tmp/nipper-ng_makeinstall.out
#   args:
#     chdir: /tmp
#     creates: nipper-ng_makeinstall.out
# - name: "nipper --version"
#   shell: nipper --version
#   register: nipperreg
