---
# [WARNING]: Could not find aptitude. Using apt-get instead fix
- name: "APT: Install aptitude package"
  apt:
   name: aptitude
   force_apt_get: yes
# distribution specific
- name: "Install mokapot requirements"
  apt:
    name: "{{ ubuntu_1604_reqs }}"
    state: latest
    update_cache: yes
  when: " ansible_os_family == 'Debian' and ansible_distribution in ['Ubuntu'] and ansible_distribution_version in ['16.04'] "
- name: "Install mokapot requirements"
  apt:
    name: "{{ ubuntu_1904_reqs }}"
    state: latest
    update_cache: yes
  when: " ansible_os_family == 'Debian' and ansible_distribution in ['Ubuntu'] and ansible_distribution_version in ['19.04'] "  

# mutual packages
- name: "git checkout nipper"
  git:
    repo: 'https://github.com/arpitn30/nipper-ng.git'
    dest: /tmp/mokapot/nipper-ng
    clone: yes
    update: no
- name: "Make nipper-ng"
  shell: make chdir=/tmp/mokapot/nipper-ng/0.11.10 >> /tmp/nipper-ng_make.out
  args:
    chdir: /tmp
    creates: nipper-ng_make.out
- name: "Make install nipper-ng"
  shell: make install chdir=/tmp/mokapot/nipper-ng/0.11.10 >> /tmp/nipper-ng_makeinstall.out
  args:
    chdir: /tmp
    creates: nipper-ng_makeinstall.out
- name: "nipper --version"
  shell: nipper --version
  register: nipperreg
