---
# https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Ubuntu_Installation
# [WARNING]: Could not find aptitude. Using apt-get instead fix
- name: "APT: Install aptitude package"
  apt:
   name: aptitude
   force_apt_get: yes
- name: "mokapot requirements"
  package:
    name: "{{ mokapot_debian_reqs }}"
    state: present
- name: "git checkout nipper"
  git:
    repo: 'https://github.com/arpitn30/nipper-ng.git'
    dest: /tmp/mokapot/nipper-ng
    clone: yes
    update: no
- name: "Make nipper-ng"
  shell: make chdir=/tmp/mokapot/nipper-ng/0.11.10 >> /tmp/nipper-ng_make.out
  args:
    chdir: /tmp
    creates: nipper-ng_make.out
- name: "Make install nipper-ng"
  shell: make install chdir=/tmp/mokapot/nipper-ng/0.11.10 >> /tmp/nipper-ng_makeinstall.out
  args:
    chdir: /tmp
    creates: nipper-ng_makeinstall.out
- name: "nipper --version"
  shell: nipper --version
  register: nipperreg
