---
- name: Install Debian dependencies
  apt:
    name: "{{ vscode_debian_dependencies }}"
    state: present
    update_cache: true

- name: Add Microsoft signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code apt repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: Install VS Code
  package:
    name: code
    state: present    
