---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common
    # - blackarch1

- name: "Build blackarch1"
  gather_facts: true
  hosts:  vg-mokapot-02
  become: yes
  roles:
    - blackarch1

# - name: "Build blackarch"
#   gather_facts: true
#   hosts:  vg-mokapot-02
#   become: yes
#   vars:
#       ansible_arch_blackarch:
#         # Temporary installation files go here: /tmp/{{ prefix }}/...
#         tmp: "BlackArch-1337"
#         # The BlackArch mirror list to use
#         mirror: "blackarch-mirrorlist"
#         # Settings for the BlackArch keyring, signature, etc.
#         keyring:
#           url: "https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz"
#           sig: "https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz.sig"
#           key:
#             id: "4345771566D76038C7FEB43863EC0ADBEA87E4E3"
#             owner: "Evan Teitelman <teitelmanevan@gmail.com>"
#         # The BlackArch categories to install, also see 'sudo pacman -Sg | grep blackarch'
#         categories:
#           - "blackarch"
#           #- "blackarch-webapp"
#           #- "blackarch-fuzzer"
#           #- "blackarch-scanner"
#           #- "blackarch-proxy"
#           #- "blackarch-windows"
#           #- "blackarch-dos"
#           #- "blackarch-disassembler"
#           #- "blackarch-cracker"
#           #- "blackarch-voip"
#           #- "blackarch-recon"
#           #- "blackarch-spoof"
#           #- "blackarch-forensic"
#           #- "blackarch-crypto"
#           #- "blackarch-backdoor"
#           #- "blackarch-binary"
#           #- "blackarch-networking"
#           #- "blackarch-misc"
#           #- "blackarch-exploitation"
#           #- "blackarch-defensive"
#           #- "blackarch-wireless"
#           #- "blackarch-automation"
#           #- "blackarch-packer"
#           #- "blackarch-mobile"
#           #- "blackarch-malware"
#           #- "blackarch-reversing"
#           #- "blackarch-sniffer"
#           #- "blackarch-code-audit"
#           #- "blackarch-social"
#           #- "blackarch-honeypot"
#           #- "blackarch-hardware"
#           #- "blackarch-fingerprint"
#           #- "blackarch-debugger"
#           #- "blackarch-firmware"
#           #- "blackarch-config"
#           #- "blackarch-bluetooth"
#           #- "blackarch-database"
#           #- "blackarch-cryptography"
#           #- "blackarch-scan"
#           #- "blackarch-automobile"
#           #- "blackarch-decompiler"
#           #- "blackarch-nfc"
#           #- "blackarch-tunnel"
#           #- "blackarch-drone"
#           #- "blackarch-radio"
#           #- "blackarch-keylogger"
#           #- "blackarch-stego"
#           #- "blackarch-unpacker"
#           #- "blackarch-anti-forensic"
#           #- "blackarch-ids"
#           #- "blackarch-spoff"
#           #- "blackarch-gpu"
#   roles:
#     - blackarch

# - name: "Build Debian GNU/Linux 10 (buster) mokapot"
#   gather_facts: true
#   hosts:  vg-mokapot-05
#   become: yes
#   roles:
#     - chromium
#     - role: burpsuite
#       burpsuite_user: vagrant
#     - ghidra
#     - role: vscode
#     # - role: vscode-extensions #Extension 'ms-vscode.go' not found.
#     #   vscode_extensions:
#     #   - ms-python.python
#     #   - ms-vscode.go
#     - docker
#     # - bettercap #"No package matching 'bettercap' is available"
#     # - empire #"No package matching 'libssl1.0.2' is available"
#     # - hcxtools #"No package matching 'wireguard' is available"
#     # - hcxdumptool #openssl/evp.h: No such file or directory", " #include <openssl/evp.h>"
#     # - wireguard #No package matching 'wireguard' is available
#     #- powershell #Depends: libssl1.0.2 but it is not installable\n
#     - impacket
#     - nullinux
#     - mokapot
#     - nipper
#     # - role: johntheripper # cannot remove '/usr/local/src/JohnTheRipper/run/*.dSYM': No such file or directory",
#     #   jtr_local_src_dir: /usr/local/src
#     #   jtr_openmpi_support_enabled: true
#     #   jtr_rexgen_support_enabled: false

# - name: "Build Ubuntu 19.10 (Eon) mokapot"
#   gather_facts: true
#   hosts:  vg-mokapot-01
#   become: yes
#   roles:
#     #- chromium #"No package matching 'chromium' is available"
#     - burpsuite

# - name: "Build Archlinux mokapot"
#   gather_facts: true
#   hosts:  vg-mokapot-06
#   become: yes
#   roles:
#     - tor
#     - hcxtools
#     # - mokapot
#     - nipper
