---
# - name: "Boot all hosts"
#   gather_facts: true
#   hosts:  all
#   become: yes
#   vars:
#     add_host_entries: true
#     add_resolv_entries: true
#   pre_tasks:
#   - name: "Setting hostname"
#     shell: "hostnamectl set-hostname {{ inventory_hostname }}"
#   roles:
#     - common

- name: "Build blackarch mokapot"
  gather_facts: true
  hosts:  vg-mokapot-01
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  roles:
    - common ##baseline role
#####################testing##########################
    - pdns
    - metasploit
#####################testing##########################

- name: "Build Debian GNU/Linux 10 (buster) mokapot"
  gather_facts: true
  hosts:  vg-mokapot-05
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  roles:
    - common ##baseline role
    # - chromium
    # - impacket
    # - nullinux
    # - nipper
    # - role: burpsuite
    #   burpsuite_user: vagrant
    # - docker
    # - ghidra
    # - maldet
    # - mokapot
#####################testing##########################
    - pdns
    - metasploit
#####################testing##########################
    # - role: vscode
    # - role: vscode-extensions #Extension 'ms-vscode.go' not found.
    #   vscode_extensions:
    #   - ms-python.python
    #   - ms-vscode.go
    # - bettercap #"No package matching 'bettercap' is available"
    # - empire #"No package matching 'libssl1.0.2' is available"
    # - hcxtools #"No package matching 'wireguard' is available"
    # - hcxdumptool #openssl/evp.h: No such file or directory", " #include <openssl/evp.h>"
    # - wireguard #No package matching 'wireguard' is available
    #- powershell #Depends: libssl1.0.2 but it is not installable\n
    # - role: johntheripper # cannot remove '/usr/local/src/JohnTheRipper/run/*.dSYM': No such file or directory",
    #   jtr_local_src_dir: /usr/local/src
    #   jtr_openmpi_support_enabled: true
    #   jtr_rexgen_support_enabled: false




# - name: "Build Ubuntu 19.10 (Eon) mokapot"
#   gather_facts: true
#   hosts:  vg-mokapot-01
#   become: yes
#   roles:
#     #- chromium #"No package matching 'chromium' is available"
#     - burpsuite

- name: "Build Archlinux mokapot"
  gather_facts: true
  hosts:  vg-mokapot-06
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  roles:
    - common ##baseline role
#####################testing##########################
    - pdns
    - metasploit
#####################testing##########################
    # - tor
    # - hcxtools
    # - mokapot
    # - nipper
