---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common

- name: "Build Ubuntu 19.10 (Eon) mokapot"
  gather_facts: true
  hosts:  vg-mokapot-01
  become: yes
  vars:
    foreman_db_pass: supersecret
  roles:
    - chromium
    - burpsuite

- name: "Build blackarch mokapot"
  gather_facts: true
  hosts:  vg-mokapot-02
  become: yes
  vars:
    foreman_db_pass: supersecret
  roles:
    - blackarch

- name: "Build Debian GNU/Linux 10 (buster) mokapot"
  gather_facts: true
  hosts:  vg-mokapot-05
  become: yes
  vars:
    foreman_db_pass: supersecret
  roles:
    - chromium
    - burpsuite

- name: "Build Archlinux mokapot"
  gather_facts: true
  hosts:  vg-mokapot-06
  become: yes
  vars:
    foreman_db_pass: supersecret
  roles:
    - tor
