---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common

- name: "Build Debian GNU/Linux 10 (buster) mokapot"
  gather_facts: true
  hosts:  vg-mokapot-05
  become: yes
  roles:
    - mokapot #baseline
    - chromium
    - role: burpsuite
      burpsuite_user: vagrant
    - ghidra
    - role: vscode
    - docker
    - impacket
    - nullinux
    - nipper
