---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common
- name: "Install mokapot"
  gather_facts: true
  hosts:  vg-mokapot-01
  become: yes
  roles:
    - mokapot
- name: "Install mokapot"
  gather_facts: true
  hosts:  vg-mokapot-02
  become: yes
  roles:
    - mokapot
- name: "Install mokapot"
  gather_facts: true
  hosts:  vg-mokapot-03
  become: yes
  roles:
    - mokapot
