---
#https://docs.ansible.com/ansible/2.3/include_vars_module.html
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - default.yml

- name: "Install system packages w apt - git problem"
  apt:
    name: git
    state: present

- name: "Install system packages w dpkg- git problem"
  package:
    name: '{{ system_packages }}'
    use: '{{ ansible_pkg_mgr }}'
    state: present


- name: "Extract the latest version of maldet into /tmp"
  unarchive:
    src: https://www.rfxn.com/downloads/maldetect-current.tar.gz
    dest: /tmp/mokapot
    remote_src: yes

- name: "move to the Maldet directory and install maldet"
  shell: "cd /tmp/mokapot/maldetect* && sudo bash install.sh && sudo ln -s /usr/local/maldetect/maldet /usr/local/bin/maldet"


# https://www.sans.org/free tools
- name: "git checkout quantumduck"
  git:
    repo: 'https://github.com/dagonis/QuantumDuck.git'
    dest: /tmp/mokapot/quantumduck
    clone: yes
    update: no
- name: "git checkout obscureV4"
  git:
    repo: 'https://github.com/dagonis/obscureV4.git'
    dest: /tmp/mokapot/obscureV4
    clone: yes
    update: no
- name: "git checkout pktIntel"
  git:
    repo: 'https://github.com/SecurityNik/pktIntel.git'
    dest: /tmp/mokapot/pktIntel
    clone: yes
    update: no
