---
#https://docs.ansible.com/ansible/2.3/include_vars_module.html
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - default.yml

- name: "Install system packages w apt - git problem"
  apt:
    name: git
    state: present

- name: "Install system packages w dpkg- git problem"
  package:
    name: '{{ system_packages }}'
    use: '{{ ansible_pkg_mgr }}'
    state: present


- name: "Extract the latest version of maldet into /tmp"
  unarchive:
    src: https://www.rfxn.com/downloads/maldetect-current.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move to the Maldet directory"
  shell: ls -lai && cd /tmp/maldetect*

- name: "Extract the latest version of Suricata into /tmp"
  shell: install sh
