---
- name: "OS fingerprinting "
  debug:
    msg:
    - " ansible_os_family: {{ hostvars[inventory_hostname].ansible_os_family }} "
    - " ansible_distribution: {{ hostvars[inventory_hostname].ansible_distribution }}"
    - " ansible_distribution_major_version: {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
    - " ansible_distribution_release: {{ hostvars[inventory_hostname].ansible_distribution_release }}"
    - " ansible_distribution_version: {{ hostvars[inventory_hostname].ansible_distribution_version }}"

- name: Check if blackarch repository is present
  command: pacman -Sl blackarch
  register: blackarch_present
  changed_when: false
  failed_when: false

- name: Download and install blackarch keyring
  block:
    - import_tasks: update_archlinux.yml
    - import_tasks: download_blackarch.yml
    - import_tasks: install_blackarch.yml
    - import_tasks: configure_blackarch.yml
  when: blackarch_present.rc != 0
