---
- name: "OS fingerprinting "
  debug:
    msg:
    - " ansible_os_family: {{ hostvars[inventory_hostname].ansible_os_family }} "
    - " ansible_distribution: {{ hostvars[inventory_hostname].ansible_distribution }}"
    - " ansible_distribution_major_version: {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
    - " ansible_distribution_release: {{ hostvars[inventory_hostname].ansible_distribution_release }}"
    - " ansible_distribution_version: {{ hostvars[inventory_hostname].ansible_distribution_version }}"

- debug:
    msg: "{{ vars[(role_path | basename).split('.')[-1].replace('-','_')] }}"
  when: DEBUG | d() | bool

- include_tasks: prepare.yml
- include_tasks: configure.yml
- include_tasks: install.yml
