---
- name: Refresh pacman keys
  command: pacman-key "{{ item }}"
  changed_when: false
  failed_when: false
  loop:
    - "--init"
    - "--refresh-keys"
    - "--updatedb"

- name: Force a full pacman update
  pacman:
    update_cache: yes
    upgrade: yes
  changed_when: false
